### ISSUE TITLE
Unable to convert Programme Ratings to csv

### ISSUE THREAD

**Issue by prakashautade** [coppeliaMLA/pybarb#17]
While downloading Programme Ratings getting the following error

![image](https://github.com/coppeliaMLA/pybarb/assets/6803863/2e18444f-853d-4223-baba-ff7cc60a1a9c)

I think here in ProgrammeRatingsResultSet.to_dataframe(), the condition `'programme_content' == "None"` is causing the issue. 
https://github.com/coppeliaMLA/pybarb/blob/0084485f3fa4cfbca4c1ba7ff540b86b94b1ff7b/pybarb/pybarb.py#L413

Changing the condition to `e['programme_content'] is not None` might fix this.

**Comment by coppeliaMLA** [comment]
Hi @prakashautade sorry I am a bit snowed under this week. However if you want to make the fix yourself I can make you a collaborator?

**Comment by prakashautade** [comment]
I am happy to contribute.

**Comment by coppeliaMLA** [comment]
Fantastic - adding you now

**Comment by prakashautade** [comment]
Can you please share when the latest changes will be available on [pypi](https://pypi.org/project/pybarb/#history)?
Thank you.

**Comment by prakashautade** [comment]
I can see the new update in the latest build on [pypi](https://pypi.org/project/pybarb/#history).
Thank you.
