### ISSUE TITLE
Missing Metadata for programme_ratings endpoint

### ISSUE THREAD

**Issue by HaroonAftabBBC** [coppeliaMLA/pybarb#26]
When attempting to create a dataframe using  the programme_ratings endpoint, it seems as though some of the metadata such as 
episode_number, episode_name and genre are missing as seen in the screenshot below: (When producing a JSON file this metadata is present)

![Screenshot 2023-08-15 at 10 41 32](https://github.com/coppeliaMLA/pybarb/assets/130052624/7ad7b01a-2c60-4d6e-bd28-f2f51d48e7bf)

**Comment by coppeliaMLA** [comment]
Thanks @HaroonAftabBBC Code did not properly reflect the json structure. I've just fixed it. Would you mind confirming that it works ok for you.

**Comment by coppeliaMLA** [comment]
Hi @HaroonAftabBBC are you upgrading using pip or by working from the latest version of the repo (either way it should work but I'm just trying to isolate the problem)

**Comment by HaroonAftabBBC** [comment]
Yes, that sounds good, thank you!

**Comment by coppeliaMLA** [comment]
Done!
